# テストで参照されるので編集注意

[hipchat]
default_nickname = "ikasan"
nickname = "く{% nickname %}コ:彡"
api_tokens = [ "token1", "token2", "token3" ] 
server_url = "https://www.hipchat.com"

[hipchat.restrict]
message_count = 20
duration = 20  # sec
stack_burst_message = false

[admin]
imkayac = [ "studio3104" ]
